name: DockerHub

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Jobs
      uses: docker/build-push-action@v2
      with:
        context: ./jobs
        push: true
        tags: brulicharis/jobsmicro:1.0

    - name: Build and Push Root Config
      uses: docker/build-push-action@v2
      with:
        context: ./root-config
        push: true
        tags: brulicharis/root-configmicro:1.0

    - name: Build and Push Tracking
      uses: docker/build-push-action@v2
      with:
        context: ./tracking
        push: true
        tags: brulicharis/trackingmicro:1.0

    - name: Build and Push Users
      uses: docker/build-push-action@v2
      with:
        context: ./users
        push: true
        tags: brulicharis/usersmicro:1.0
